### PR TITLE
Uncaught exception documentation

### LINKED ISSUE #1308: uncaughtException to close connection
Just want to bring the idea of closing the tcp connection on an uncaught exception.

If an uncaught exception occurs, that current tcp connection is killed and could cause clients to hang when trying to connect in subsequent requests.

This might make the library too opinionated though since it's adding it's own http standards - happy to discuss and make a PR.

Current way to keep subsequent client connections from hanging when an uncaughtException is thrown:
```
server.on('uncaughtException', (req, res, route, err) => {
  res.setHeader('Connection', 'close');
  res.send(err);
});
```

### PR DESCRIPTION
**Pull request by retrohacker**
This PR introduces a "Best Practices" guide, it is written from the perspective of running restify in production.

Complements #1319 

Fixes #1308

### CODE REVIEW

**Comment by yunong** [comment]
@DonutEspresso is our resident renaissance man when it comes to documentation, tagging him for this review.

**Comment by retrohacker** [comment]
Ah! This appears to have included  the content from #1319 😞

**Comment by retrohacker** [comment]
Found out in #1319 that domains are being deprecated. A large chunk of this has become irrelevant, `server.on('uncaughtException'` needs to be changed to `process.on('uncaughtException'` and graceful cleanup needs to happen there. Will revisit tomorrow.

**Comment by DonutEspresso** [comment]
This is a great summary of the Joyent docs! That said, I think I'd be inclined to just reference those docs given the pending deprecation, and simply have a one or two liner like "we recommend following the recommended best practices [link]. If you choose to use the uncaughtException feature, please be aware of the trade offs [here][here][here]". I'm not even sure we need to get into `process.on('uncaughtException'`, at least from the perspective of restify docs. Thoughts?

**Comment by retrohacker** [comment]
Thanks for looking at this @DonutEspresso,

I was planning on revisiting this today :smile: I agree that a collection of links may contain enough information for a user to learn proper best practices for running a Node.js `net` or `tls` server in production, but I think collecting them into an opinionated guide would help restify establish it's ethos as a framework designed for running reliable REST services in production. I'm not sure if the time investment (I'm estimating ~45 minutes) would justify that though.

If we decide to push forward with this, I was planning on putting in a quick example showing how you can stop accepting new incoming connections in restify, and how to let your process shut itself down with a proper exit code (not having to explicitly call `process.exit`) once all existing connections have drained, so users know how to avoid having a restify service stuck between `uncaughtException` and a clean exit when the EventLoop never runs out of work to do. Also, possibly an example that immediately and cleanly closes all active connections and shuts down instead of letting the connections drain (to prevent clients from hanging).

Thoughts?

**Comment by retrohacker** [comment]
Based on the conversation over in #1319, I think its safe to close this PR.

**Pull request closed without merging**
