### PR TITLE
Bugfix - https://github.com/restify/node-restify/issues/1296

### PR DESCRIPTION
**Pull request by Crazedpeanut**

### CODE REVIEW

**Comment by retrohacker** [comment]
Hey @Crazedpeanut,

Thanks for this! It might be helpful if you give an example of

1. the _expected_ behaviour before this PR
2. the _actual_ behaviour before this PR

This could be a simple repro case we can run that demonstrates the bug.

**Comment by Crazedpeanut** [comment]
Sure thing! I am a bit new to contributing to open source projects

**Comment by retrohacker** [comment]
Hey @Crazedpeanut,

I'm closing this as stale for now. If you have time to create the requested examples we can re-open and do a proper review of this PR :smile:

**Comment by retrohacker** [comment]
We are always excited to see first time contributors, especially those who are new to open source! If you need any assistance in getting a repro case together, let us know :heart:

**Comment by Crazedpeanut** [comment]
Sorry for the super long response, here is an example of the error I am getting.

Let me know if you need more information!

[Reproduce-Restify-No-Proxy-Error.txt](https://github.com/restify/node-restify/files/1087036/Reproduce-Restify-No-Proxy-Error.txt)

**Comment by retrohacker** [comment]
Cool beans! I did verify that this is a bug, and that this does in fact fix it! :tada:

The new code lives in this file here: https://github.com/restify/clients/blob/master/lib/HttpClient.js#L355

Would you mind opening a PR against that repo @Crazedpeanut? With this the only outstanding thing will be to provide a test that

* Passes when your fix is introduced
* Fails without your fix

Your repro case is pretty close to this, it just needs to use a restify server instead, which the tests in the clients repo automatically setup for you. There are some good examples of how to do this in the existing tests for the repo: https://github.com/restify/clients/blob/master/test/index.js#L267-L273

Closing this for now, will merge when a PR is opened against the clients repo with a test :smile:

Thank you for all of your hard work on this @Crazedpeanut :heart:

**Pull request closed without merging**
