### PR TITLE
Node8 response headers

### PR DESCRIPTION
**Pull request by retrohacker**
Supersedes #1369

### CODE REVIEW

**Comment by retrohacker** [comment]
Failing tests are unrelated to PR

**Comment by vhenriet** [comment]
Could we hae this fix also for 4.x?

**Comment by avimar** [comment]
The upgrade guide looks a little long, I wasn't planning on upgrading yet.
http://restify.com/docs/4to5/

Not that this is the best place to ask, but is there anything more to do to upgrade to 6.x?

**Comment by retrohacker** [comment]
Hey @avimar :smile:

We use semantic versioning and conventional commits so it should be pretty easy to track what has changed between releases by looking at our commit history on master. https://github.com/restify/node-restify/commits/master

There is a lot to unpack there when moving from 4->5, which is why the migration guide exists, but 5-6 doesn't contain many changes to the API. Most changes were backwards compatible (unless you depended on internals or undocumented behaviour) and the ones that aren't are labeled `BREAKING CHANGE` in the commit history. Most of the breaking changes for 5->6 were trivial but we erred on the side of caution.

Hope this helps :heart:

**Pull request merged**
