### PR TITLE
backport: fix: handle multibyte chars properly in gzip decoder

### PR DESCRIPTION
**Pull request by cjihrig**
This is a partial backport of restify/clients@c4795f2 to the
v4.x branch.

## Pre-Submission Checklist

- [ ] Opened an issue discussing these changes before opening the PR
- [x] Ran the linter and tests via `make prepush`
- [x] Included comprehensive and convincing tests for changes

## Issues

Closes:

* Issue # https://github.com/restify/clients/issues/132 for v4.x

> Summarize the issues that discussed these changes

Quoting https://github.com/restify/clients/issues/132#issue-248127824:

StringClient directly decodes chunks to utf8 strings which is not safe in the case of a chunk boundary falling within a multibyte character. Instead it should be using the string_decoder api which accounts for this. https://nodejs.org/api/string_decoder.html

# Changes

> What does this PR do?

Backports an existing fix to an older release line.

### CODE REVIEW

**Comment by DonutEspresso** [comment]
LGTM - its been awhile since we did a 4.x release - should be able to get a patch release out for you. @hekike any concerns with this?

**Comment by DonutEspresso** [comment]
Also, thank you @cjihrig for a first time PR here. Appreciate the work you do on core.  🎉

**Comment by hekike** [comment]
@DonutEspresso sounds good to me!

**Comment by hekike** [comment]
But you should check out 7.x, we made some nice performance improvements there ;)

**Comment by DonutEspresso** [comment]
restify@4.3.3 published

**Comment by cjihrig** [comment]
Thank you 🙏

**Pull request merged**
