### PR TITLE
Update package.json to spdy ^3.3.0

### PR DESCRIPTION
**Pull request by kolbma**
Update spdy in the stable branch to get HTTP/2 support for restify.

### CODE REVIEW

**Comment by kolbma** [comment]
Any idea why the test client.test.js
✖ GH-115 GET path with spaces
fails with stable node?

**Comment by DonutEspresso** [comment]
Thank you for the pull request! 

We're actually looking to release 5.x before end of this month - if you can wait, that will come with the latest version of spdy and a bunch of bug fixes and improvements. If you're inclined to stay on 4.x, I'll need @yunong to chime in and take a look at why the timer tests needed to be updated to pass.

**Comment by kolbma** [comment]
Ok thanks for the information.
I can use a 5.x release.
But the timer logic with "greater" is wrong because the timer resolution is too big for fast processors so that the instructions might have finished just in time with the timer.  So there is the need of greater-equals. A few code lines above there is already a comment about this timing issue and the resolution was to use an timer with 1100 instead of 1000. But greater-equal should be the correct fix.

**Comment by DonutEspresso** [comment]
restify@4.1.0 was just released with latest spdy to address this issue.

Official 5.x coming in a week or so.

**Pull request closed without merging**
