### PR TITLE
Fix: Bind server to middleware context

### PR DESCRIPTION
**Pull request by retrohacker**
Fixes #GH-1639

### CODE REVIEW

**Comment by retrohacker** [comment]
cc:// @davidmarkclements

**Comment by DonutEspresso** [comment]
Awesome, thanks for tackling this! Might want to run prettier to make sure styling is passing. 

I thought @hekike had a benchmark at some point, we could use that as a quick comparison of bind vs call/apply. With call/apply we wouldn't have to redefine the function name, but not sure how feasible that would be given that the router executes the chains now. Assuming a user land provided router is where we want to head I don't think that may not work either unless we decided to close over every handler.

**Comment by retrohacker** [comment]
I tried using `call/apply` but ran into the problem of trying to get the `server` variable down into the chain executor. IIRC I had to pass it into 2 different constructors and a function in order to get it into scope. I could just attach it to the handler as a value (i.e. `handler.server = server`), its hacky but should work if we want to take that path. Then it would be `handler.apply(handler.server ...)`.

**Comment by jrnail23** [comment]
is there a possibility of getting this PR merged?  I'm currently upgrading an app that depends on `this` in route handler chains being the server instance, and it's now `undefined` since installing v7.1.1.

**Pull request closed without merging**
