### PR TITLE
Removing route from LRU cache on unmount.

### PR DESCRIPTION
**Pull request by lgomez**
This is an update on a previous PR with all the latest updates from 5.x. This time tests pass.

### CODE REVIEW

**Comment by DonutEspresso** [comment]
Thanks for the PR! We'd really appreciate it if you can add a test or two to validate the behavior.

**Comment by lgomez** [comment]
I was trying to do so but, when `.dump()`'ing the cache from within the server.test.js file in the `rm` test, all I get is an empty array. Any ideas on how to test that? I thought the `'/foo/:id'` route would've been cached (after performing the test request but it's not.

I'll keep trying but, if you have any pointers, it'd be great.

**Comment by lgomez** [comment]
Never mind. Figured it out.

**Comment by lgomez** [comment]
So... My code was actually broken. Added the test and fixed it. Let me know if you need anything else. Thank you!

**Comment by DonutEspresso** [comment]
Thank you, this looks great! LGTM, a second  👀  and let's get this in.

**Comment by micahr** [comment]
Looks good to me.

**Comment by DonutEspresso** [comment]
@lgomez thanks for the help! Much appreciated.

**Comment by lgomez** [comment]
My pleasure. Thank you for all the work on Restify.

**Pull request merged**
