### PR TITLE
Adding support for Proxy Protocol

### PR DESCRIPTION
**Pull request by fidian**
By setting a truthy value for "proxyProtocol" in your options, the
transport selected (http / https / spdy) will be wrapped.

```
...
"proxyProtocol": true
...
```

A user may also configure the settings by specifying an object:

```
...
"proxyProtocol": {
    "strict": true,
    "ignoreStrictExceptions": false,
    "overrideRemote": true
}
...
```

For more information regarding the options, check out
[findhit-proxywrap](https://github.com/findhit/proxywrap).

### CODE REVIEW

**Comment by fidian** [comment]
Updated this request by merging in the changes from #1047.  If there is any discussion with this patch, I would be happy to chat on IRC (fidian).  I'll try to hang out there until this is rejected or accepted.

**Comment by fidian** [comment]
Updated again.  I love how easy GitHub makes these merges.

**Comment by fidian** [comment]
I do not know what broke the build.  The tests appear to have executed successfully and there's some thing about color-convert being extraneous, but that appeared only after I did the merge from the 5.x branch.  In theory the 5.x branch should be failing as well, but it looks like it is passing.

Today's the last day I will be hanging out in IRC trying to get feedback and any discussion from the developers.

**Comment by micahr** [comment]
I apologize for the delay in getting back to you regarding your PR and communication via IRC. 1/3rd of the active maintainers are on vacation, and the other 2/3rds are heads down at work, making it difficult to dedicate time to OSS work. Thank you for taking the time to file the PR and your perseverance.

----

Would it be possible for you to add a few tests around this new functionality? Additionally, can you add a short description in the docs for the new configuration?

**Comment by fidian** [comment]
You hit upon two of the three points that I would have loved to discuss in IRC.

I am curious how I would add those tests.  To properly run a test like that, it would need to simulate a TCP connection, hand off a Proxy Protocol line and a web request, then inspect the request object to ensure that it is reporting the correct IP addresses and ports.  This would need to be done for https, http and spdy.  How do your tests mock out built-in node modules?  I don't see a way to substitute the objects or pretend to open a connection to a server.

Updating the documentation is also a dilemma for me.  Proxy Protocol is such an obscure thing (primarily used in ELBs and HA Proxy fronted services) that I figured that it should be documented like SPDY.  However, in my opinion, the documentation on SPDY is terrible and that turned me off from doing it that way from the beginning.  How would you recommend this is approached?

Lastly, I was wondering if you were going to pull out the "createServer" bit into plugins or something similar, allowing a person to make a SPDY, Proxy Protocol'd HTTP, HTTPS or any other type of server.  Perhaps an email gateway could be made with the right plugins.  I was wondering if there was forward progress in that area or if that wasn't currently a direction you wanted to take with the framework.

**Comment by fidian** [comment]
Two months without a reply.  Is it poor etiquette for me to bump this issue?

**Comment by retrohacker** [comment]
Hey @fidian,

Is this still something you would like to see merged? On behalf of maintainers, I'm terribly sorry this has sat here untouched for over 1 year. :disappointed: 

If you would like to see this merged and are willing to champion the work, I'll work through the questions you asked above and help make sure this gets merged. Otherwise we can move it to our feature request doc until someone volunteers to carry it over the finish line. We are still in a place where the code base appears to still be compatible with this PR so it seems to be in the final stretch. Also, HTTP/2 is now in Node.js v8 under a feature flag :smile:

I'm assigning this to myself for now :heart:

**Comment by fidian** [comment]
What work needs to be championed? It looks like there's only two minor conflicts if you were to try merging the code.

**Comment by retrohacker** [comment]
Hey @fidian! Thank you for re-engaging on this issue :heart: I'm sure getting notifications from this over a year later is probably frustrating.

The outstanding work for this PR includes resolving the minor merge conflicts, implementing tests to cover the work, and adding a quick blurb in the docs about how to use this.

From your original questions, an integration test is good enough for this case given the complexity of the feature. Most of our current tests are integration tests as it stands. For the docs, we have a fancy new doc-site that automatically generates based off of the ./docs directory in this repo. To run it locally, recursively checkout https://github.com/restify/restify.github.io and follow the instructions in the README :smile:

**Comment by fidian** [comment]
My questions from April 1, 2016 were not addressed. These revolve around trying to match SPDY because both Proxy Protocol and SPDY modify the TCP traffic and make things more difficult in about the same way. Because these are still outstanding for over a year, I don't feel very motivated to continue working on this pull request.

    * How does one write tests when it alters the TCP communication? (SPDY has none.)
    * How does one write documentation explaining the options and showing examples of how this works? Is there any place where the options are described more thoroughly? (SPDY has exactly 2 lines in the `docs/` folder, but only 1 really for the option.)
    * Is the project going to pull the `createServer` call out into a plugin, allowing SPDY, Proxy Protocol, or other types of connections going forward and reduce the dependencies of the project?
    * The 5.x branch has two failing tests and deprecation notices. With my changes, the same number of tests fail and there's still deprecation notices. I didn't investigate the failures because they came from the 5.x branch.

I appreciate that you're trying to revive an ancient pull request. However, it seems like you didn't even try to do the merge yourself.  Here's both conflicts (3-way diff). Just to explain the diff a bit, the first chunk is what's in 5.x, the middle is the common ancestor between the branches, and the last bit is from my branch.

`lib/server.js`

```
++<<<<<<< HEAD
 +var semver = require('semver');
++||||||| merged common ancestors
++=======
+ var proxyWrap = require('findhit-proxywrap');
++>>>>>>> origin/proxywrap
```

`package.json`

```
++<<<<<<< HEAD
 +    "formidable": "^1.0.17",
++||||||| merged common ancestors
++    "formidable": "^1.0.14",
++    "http-signature": "^0.11.0",
++=======
+     "findhit-proxywrap": "^0.3.11",
+     "formidable": "^1.0.14",
+     "http-signature": "^0.11.0",
++>>>>>>> origin/proxywrap
```

One wants both additions for `lib/server.js`. In `package.json` the only conflict is that I've added `findhit-proxywrap` near a line that was modified in another commit on the 5.x branch.

:+1: for communicating again after a year.
:-1: for not trying the merge yourself.
:-1: for not answering my questions.

I've removed the conflicts. They were trivial. I've added a one-line description of the option. This brings it to parity with the SPDY option. I no longer use this server and switched to [restiq](https://github.com/andrasq/node-restiq) for several reasons. Further modifications don't seem worthwhile; why hold me to a higher bar than the current codebase?

**Comment by retrohacker** [comment]
Cool beans! Thank you for resolving the initial conflicts. I'd like to give context on your feedback if that is okay:

> I appreciate that you're trying to revive an ancient pull request. However, it seems like you didn't even try to do the merge yourself.

That is correct, I have no vested interest in seeing this feature land. It is apparent that you do not either. Thus my original suggestion to move this feature request to our FEATURE_REQUEST.md doc until someone comes along who both needs this feature and is willing to implement it.

I personally use restify at work, and I'm volunteering my limited extra time to man the PR and Issues in an attempt to remove obstacles standing in the way of others who would like to contribute. For me, I want to make sure people have context around the code base when trying to figure out how to implement features. As you pointed out, the code base, branding, and documentation can use some love. I'm incrementally working on doing that as I land features that are relevant to me, and I am asking others to do the same.

I'm relatively new here. Looking at the amount you engaged with the project and community while using this project, you should have been made a maintainer a long while back. I apologize that didn't happen, if you ever come back to using restify there is a place for you here. :heart:

For your questions:

> How does one write tests when it alters the TCP communication? (SPDY has none.)

I'm not sure. I've never worked with SPDY. If a feature is being landed for supporting a server protocol, I would assume there is a correspond client somewhere in the npm ecosystem that can handle receiving requests from that protocol. I would suspect that an integration test which starts the server using SPDY and then uses a client supporting SPDY would be able to verify that the server is doing what you would expect with the protocol.

> How does one write documentation explaining the options and showing examples of how this works? Is there any place where the options are described more thoroughly? (SPDY has exactly 2 lines in the `docs/` folder, but only 1 really for the option.)

I'm personally open to suggestions here. I would suspect this belongs in https://github.com/restify/node-restify/blob/5.x/docs/api/server.md but, as you pointed out, this is already under-documented.

> Is the project going to pull the `createServer` call out into a plugin, allowing SPDY, Proxy Protocol, or other types of connections going forward and reduce the dependencies of the project?

To my knowledge this hasn't been discussed. Would be cool to break this out into a feature request if anyone wants to see that happen. I suspect the implication would be that every protocol restify supports would have to expose a `require('http')` compatible interface. But I don't think that would be too jarring.

> The 5.x branch has two failing tests and deprecation notices. With my changes, the same number of tests fail and there's still deprecation notices. I didn't investigate the failures because they came from the 5.x branch.

We have some transient failures. I haven't had time to track them down, but re-running the failed test usually gets it to pass.

---

I'm going to go ahead and close this PR and move it to the FEATURE_REQUEST.md as originally proposed.

**Comment by retrohacker** [comment]
https://github.com/restify/node-restify/commit/37c5af69c83e303731e2bfe4ba97f93ccc9ba8f3

**Pull request closed without merging**
