### PR TITLE
Fix: 652 - Incorrect error on route with no versions

### PR DESCRIPTION
**Pull request by karthikiyengar**
## Pre-Submission Checklist

- [x] Opened an issue discussing these changes before opening the PR
- [x] Ran the linter and tests via `make prepush`
- [x] Included comprehensive and convincing tests for changes

## Issues

Closes: https://github.com/restify/node-restify/issues/652

# Changes

Throws in InvalidVersionError instead of a MethodNotAllowedError when a route with no versions is called with the 'Accept-Version' header

### CODE REVIEW

**Comment by DonutEspresso** [comment]
Thank you for taking this up, @karthikiyengar! Always great to see new contributors. 🎉

What's your comfort level on adding tests that cover this new behavior? It would be great to see a test for both a mismatching version as well as a missing version, as reported originally in #652.

**Comment by karthikiyengar** [comment]
@DonutEspresso - Sure, I can add some tests. Thank you for the library, I've had much fun using it :-)

**Comment by karthikiyengar** [comment]
@DonutEspresso - Just a quick question - I'm planning to actually have the servers listen and call them with client.get in the tests. Is this what you had in mind?

**Comment by karthikiyengar** [comment]
Tests added 😄

**Comment by retrohacker** [comment]
:tada: This is awesome @karthikiyengar !!!!!!

Thanks for doing this, the PR looks good to me!

**Comment by DonutEspresso** [comment]
Fantastic. Thanks @karthikiyengar!  🎉

**Pull request merged**
