### PR TITLE
GH-959: fixes issue where cached routes were not setting maxVersion on req

### LINKED ISSUE #959: matchedVersion() returns range instead of version on every call but the first
When calling req.matchedVersion() the second time, it returns the range. It should always return the version.
	server.get({
		"path": "/test",
		"versions": ["0.1.0", "0.1.1"]
	}, function(req, res, next) {

		// requested version (Unaltered Accept-Version header)
		req.version(); 

		// the matched version (This should only return a version, not a range)
		// problem is that this function returns the range on the second call to this route because of caching
		req.matchedVersion();
		
		next();
	})

### PR DESCRIPTION
**Pull request by DonutEspresso**
Fixes #959

### CODE REVIEW

**Comment by micahr** [comment]
LGTM

**Comment by doodlemeat** [comment]
Awesome :+1:

**Comment by yunong** [comment]
Looks good. Would love to see an accompanying docs update for this feature.

On Wednesday, December 9, 2015, Anthon Fredriksson <notifications@github.com>
wrote:

> Awesome [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/restify/node-restify/pull/964#issuecomment-163150876>.
>


-- 
Via mobile

**Comment by doodlemeat** [comment]
This is the documentation for the feature. http://restify.com/#routing (scroll down)

**Pull request merged**
