### PR TITLE
Documented the ability to specify RegExp for named parameter

### PR DESCRIPTION
**Pull request by Jokero**
https://github.com/restify/node-restify/blob/5.x/lib/router.js#L90

I am amazed at how many things are not documented in restify...

### CODE REVIEW

**Comment by Jokero** [comment]
But I can't use backslashes:
```js
server.get('/hello/:name(\\d+)', send);
```
Because `url` module convert them to forward slashes

**Comment by retrohacker** [comment]
Hey @Jokero,

Yes, the restify documentation definately needs some love, as does the website design and overall branding of the project. It is absolutely on our radar. Some of the heavier technical challenges for 5.x will probably take precedence first followed closely by a documentation overhaul. The rationale is that restify is currently being used in production in a lot of business critical places, and the teams supporting and using restify have been using the code base as the definitive source of truth in lieu of proper documentation. This is working fine :tm: for now from the perspective of those heavily invested in the framework, but we understand this isn't ideal for many people and is hindering adoption. We welcome contributions like this one :heart: they are definitely a step in the right direction.

I'm going to try to validate and proof read this PR today, will let you know soon!

**Comment by retrohacker** [comment]
Tested with:

```javascript
var server = require('restify').createServer({ name: 'foobar' })

server.get('/hello/:name([a-zA-Z0-9]+)', function(req, res, next) {
  console.log(req.params)
  res.send(200)
  return next()
})

server.listen(8080)
```

**Comment by retrohacker** [comment]
Hmm, terribly sorry @Jokero, after reviewing I went to resolve the conflicts and it appears this file no longer exists. Part of the work I described above is already underway and it seems the project has moved out from under this PR. I'm going to close this for now, we can revisit later. :heart:

**Comment by retrohacker** [comment]
I'll add this to the `FEATURE_REQUESTS.md` file for now

**Pull request closed without merging**
