### PR TITLE
jsonp() compatibility with res.json()

### PR DESCRIPTION
**Pull request by sean3z**
This allows `res.json()` to continue functioning when used with the `restify.jsonp()` plugin/middleware.

###### Proposal
With this change, if the `application/javascipt` Content-Type is already added (as through the jsonp plugin), we don't add the `application/json` type when `res.json` is invoked.

###### Advantages
Basically, if you're exposing an API that can be hit through JSONP _and/or_ JSON, you can still use `res.json()`. The following example currently breaks prior to this change:

```js
// server
server.use(restify.queryParser());
server.use(restify.jsonp());

server.get('/endpoint', function (req, res, next) {
  res.json({x: 'meow'})
});

// client
request.get('/endpoint?callback=angular.callback._0', function  (err, res, body) {
  // server app fails due to typeof error
  // lib/response.js (line 117): TypeError [].split()
});
```

### CODE REVIEW

**Comment by DonutEspresso** [comment]
The jsonp plugin already adds a content-type header, and since restify has a built in formatter for jsonp, just calling `res.send()` will automatically format the output correctly. `res.json()` isn't what you want in any case, since json and javascript are two different content types.

**Comment by sean3z** [comment]
Yup, this is a proposal is primarily for developer convenience. For applications that have `res.json()` littered throughout their code base and later introduce the jsonp formatter. As it stands, if you attempt to use both, restify simply crashes - so this semi-corrects that also by allowing both to co-exist.

**Comment by micahr** [comment]
I'm in favor of not conflating json and jsonp, as they are very different responses. @DonutEspresso's suggestion of using `res.send` is the best approach for ensuring that the response is exactly what you are intending, instead of having `res.json` perform differently based on query parameters / content-type.

**Comment by sean3z** [comment]
@micahr @DonutEspresso Fair enough. I've made a slight change to the original direction by ensuring that `res.json()` continues to work (as expected) when the `jsonp()` plugin is used. As it stands, this functionality does not work.

**Comment by DonutEspresso** [comment]
I believe this issue will be fixed once #987 lands - can you take a look?

**Comment by sean3z** [comment]
Yup, looks like that will take care of it. Thanks!

**Pull request closed without merging**
