### PR TITLE
Fixes the broken test for node version 8

### PR DESCRIPTION
**Pull request by retrohacker**
@rajatkumar's fix for failing tests in v8

### CODE REVIEW

**Comment by retrohacker** [comment]
Holy crapola! Green CI! :man_dancing:

**Comment by rajatkumar** [comment]
Yep, moving to error codes is good idea, but it is only in version 8 do we have specific `Nodejs Error Codes`.

**Comment by retrohacker** [comment]
Small fix and is blocking Node.js version 8 support.

Merging at EOD.

**Comment by retrohacker** [comment]
This was fixed in another PR

**Pull request closed without merging**
