### PR TITLE
fix: format falsy constants properly in json formatter

### PR DESCRIPTION
**Pull request by ziacik**
## Pre-Submission Checklist

- [x] Opened an issue discussing these changes before opening the PR
- [x] Ran the linter and tests via `make prepush`
- [x] Included comprehensive and convincing tests for changes

## Issues

Closes:

* Issue #1791

# Changes

Json formatter now formats `0` as `0`, `false` as `false`, empty string as `""`, `undefined`, `null` and `NaN` as `null`. Note that although the formatter formats `undefined` as `null` to generate valid JSON constant, `res.send(200, undefined)` flushes empty response before the formatter gets into action.

### CODE REVIEW

**Comment by robpaveza** [comment]
This is a good update; I'd like to see it merged. (I'd vote +1 but I don't have write access anyway).

**Comment by retrohacker** [comment]
Thanks for the contribution @ziacik and for the review @robpaveza!

**Comment by retrohacker** [comment]
Will merge this if we can resolve the merge conflicts.

**Comment by ghermeto** [comment]
@ziacik if you can resolve the conflicts we can merge this PR.

**Comment by ziacik** [comment]
@ghermeto Conflict resolved

**Comment by ziacik** [comment]
@ghermeto @retrohacker Is there anything else you need me to do?

**Comment by ghermeto** [comment]
sorry, I missed the notification

**Comment by ghermeto** [comment]
IMO this is technically a breaking change, so we will target 9.X

**Pull request merged**
