### PR TITLE
Bring plugins back into repo

### PR DESCRIPTION
**Pull request by retrohacker**
## Pre-Submission Checklist

- [X] Opened an issue discussing these changes before opening the PR
- [X] Ran the linter and tests via `make prepush`
- [X] Included comprehensive and convincing tests for changes

## Issues

Closes:

* Issue #1317

Migrating the plugins out of this repo created a lot of problems when migrating to 5.x, we are pulling them back in for the time being. Breaking each of these out into their own userland modules is under discussion (cc: @stevehipwell)

# Changes

Brings the plugins back into the 5.x branch

# Future work

* Migrate both the project's tests and plugin's tests to istanbul for code coverage
* Standardize on a testing framework (mocha vs nodeunit vs other)
* Provide code coverage for plugins (blocked by above items)

### CODE REVIEW

**Comment by retrohacker** [comment]
On the fence between investing the time to reconcile tests and coverage now, vs landing this and improving later. There is a lot of tedious work to do there, and it doesn't affect the validity of the project. It _will_ make landing future features harder and should be prioritized short-term, but plugins do work as-is (test validate that). Should that block 5.x?

**Comment by DonutEspresso** [comment]
+1 to all the above. Let's land first and get a release out, we can circle back on the internal story for testing CI/CD afterwards.

**Comment by yunong** [comment]
Thanks for doing this! 👍  Did I miss it or did we bring the plugins docs back into this repo as well?

**Comment by retrohacker** [comment]
@yunong I hadn't considered migrating those as we are planning on releasing new docs in the not-so-distant future. I'll work on bringing those over now.

**Comment by retrohacker** [comment]
Migrated documentation approx 1:1

Will be cleaned up as part of the website release.

**Pull request merged**
