### PR TITLE
style: fix failing check-style

### PR DESCRIPTION
**Pull request by retrohacker**
It looks like master's `make prepush` fails with a style issue. This PR fixes that and unblocks #1668

### CODE REVIEW

**Comment by retrohacker** [comment]
Not sure how we managed to merge something that broke the master branch? Or did an eslint update change styles out from under us? Either way, this should fix things :smile:

**Comment by hekike** [comment]
@retrohacker we have seen this earlier with prettier that why I removed carrots from package.json from prettier related packages.

**Comment by retrohacker** [comment]
Failing Node.js v10 tests, unrelated to this PR, merging.

**Comment by retrohacker** [comment]
Actually looks like this might stomp on #1672 if you want to just fix the style issues with that PR?

**Pull request merged**
