### PR TITLE
add req.query to auditlogger

### LINKED ISSUE #812: Being able to also log query parameters in the audit logger
Is there any existing functionality to do this?

### PR DESCRIPTION
**Pull request by DonutEspresso**
Fixes #812.

### CODE REVIEW

**Comment by DonutEspresso** [comment]
Same failure on the req.timers test, this time for 0.12. Is this a known issue?

**Comment by micahr** [comment]
Re-ran the tests through Travis-CI and everything passed. Looks like it was just a timing thing.

**Comment by micahr** [comment]
Can you add `GH-812` to the test descriptions?

**Comment by yunong** [comment]
code lgtm, I would update the audit logger section in the logs to include the query parameters. Once that's done, feel free to merge.

**Pull request merged**
