### PR TITLE
q-value choice on wildcards ignores default q-value of 1

### PR DESCRIPTION
**Pull request by kevinpeno**
See #769 

Server responds with highest priority q-value when wildcards are used, but ignores setting the default q-value to 1 for mime-types without q-value specified.

Example:
Client: `*/*`
Server: `application/json, text/plain; q=0.9, application/octet-stream; q=0.2`
Result: `text/plain`
Expected: `application/json`

### CODE REVIEW

**Comment by kevinpeno** [comment]
Locally this test fails every time. Not sure why travis is giving a green light.

**Comment by yunong** [comment]
@kevinpeno For some reason I only see the tests as part of this commit, and not the actual restify changes. Are we missing files from the commit? Also, could you please prefix the test with the issue #? e.g. '#771 qvalue...'

**Comment by kevinpeno** [comment]
@yunong I didn't include a fix per our convo (not sure where to apply it). Any pointers on ideas/where to apply the fix is welcome. I'll update to add the issue number to the test.

**Comment by kevinpeno** [comment]
Unfortunately I run windows at home and am having issues running `npm test` so I'll take a look at both a fix and fixing the test name tomorrow.

**Comment by kevinpeno** [comment]
@yunong updated the test per request and added code to make the test pass. I made `q-value` default to 1 per RFC 2616 sec 14 (emphasis added):

> Each media-range MAY be followed by one or more accept-params, beginning with the "q" parameter for indicating a relative quality factor. The first "q" parameter (if any) separates the media-range parameter(s) from the accept-params. Quality factors allow the user or user agent to indicate the relative degree of preference for that media-range, using the qvalue scale from 0 to 1 (section 3.9). *The default value is q=1.*

This is very likely a breaking change as people may have used this bug as a work around for `q-value` ordering

**Comment by micahr** [comment]
Thank you for the PR @kevinpeno . Can you fix up the merge conflicts so this can be integrated?

**Comment by kevinpeno** [comment]
Sure thing. I'll work on that today. Sorry for the delay!

**Comment by kevinpeno** [comment]
@micahr All merged.

**Pull request merged**
