### PR TITLE
refactor(lib): forbid anonymous function in lib code

### PR DESCRIPTION
**Pull request by hekike**
## Pre-Submission Checklist

- [ ] Opened an issue discussing these changes before opening the PR
- [x] Ran the linter and tests via `make prepush`
- [x] Included comprehensive and convincing tests for changes

Forbids and refactors anonymous functions.

Anonymus functions make debugging harder with stack traces, however, I've to admit that this ESLint rule is a little bit too aggressive as anonymous `map`, `sort`, `forEach` etc. functions don't decrease observability in stack-traces.

# Changes

- ESLint rule to forbid anonymous functions
- Refactor `lib` code to avoid anonymous functions 
- Add disable rule to test files

### CODE REVIEW

**Comment by retrohacker** [comment]
`make prepush` is failing for me locally because of style.

**Comment by retrohacker** [comment]
Re-ran on travis and it still passed?

**Comment by retrohacker** [comment]
`output.log`

<summary>
<code>
NO_STYLE=true ./node_modules/.bin/eslint '.'

/home/wblankenship/Development/node-restify/lib/formatters/text.js
  24:5  warning  Unexpected 'todo' comment  no-warning-comments

/home/wblankenship/Development/node-restify/lib/plugins/conditionalRequest.js
  115:9  warning  Unexpected 'todo' comment  no-warning-comments

/home/wblankenship/Development/node-restify/lib/server.js
  238:1   warning  Unexpected 'fixme' comment  no-warning-comments
  863:17  warning  Unexpected 'todo' comment   no-warning-comments

/home/wblankenship/Development/node-restify/test/server.test.js
  2096:17  warning  Unexpected 'todo' comment  no-warning-comments

✖ 5 problems (0 errors, 5 warnings)

NO_LINT=true ./node_modules/.bin/eslint '.'

/home/wblankenship/Development/node-restify/lib/plugins/authorization.js
  82:62  error  Trailing spaces not allowed  no-trailing-spaces
  83:38  error  Trailing spaces not allowed  no-trailing-spaces
  90:67  error  Trailing spaces not allowed  no-trailing-spaces
  96:3   error  Trailing spaces not allowed  no-trailing-spaces

/home/wblankenship/Development/node-restify/lib/plugins/bodyParser.js
  27:3   error  Trailing spaces not allowed  no-trailing-spaces
  28:79  error  Trailing spaces not allowed  no-trailing-spaces
  29:34  error  Trailing spaces not allowed  no-trailing-spaces
  33:3   error  Trailing spaces not allowed  no-trailing-spaces
  34:50  error  Trailing spaces not allowed  no-trailing-spaces
  35:78  error  Trailing spaces not allowed  no-trailing-spaces
  37:68  error  Trailing spaces not allowed  no-trailing-spaces
  38:66  error  Trailing spaces not allowed  no-trailing-spaces
  40:3   error  Trailing spaces not allowed  no-trailing-spaces
  45:80  error  Trailing spaces not allowed  no-trailing-spaces
  47:80  error  Trailing spaces not allowed  no-trailing-spaces
  49:79  error  Trailing spaces not allowed  no-trailing-spaces
  50:59  error  Trailing spaces not allowed  no-trailing-spaces
  51:79  error  Trailing spaces not allowed  no-trailing-spaces
  52:78  error  Trailing spaces not allowed  no-trailing-spaces
  53:75  error  Trailing spaces not allowed  no-trailing-spaces
  55:75  error  Trailing spaces not allowed  no-trailing-spaces
  56:77  error  Trailing spaces not allowed  no-trailing-spaces
  57:52  error  Trailing spaces not allowed  no-trailing-spaces
  58:48  error  Trailing spaces not allowed  no-trailing-spaces
  59:75  error  Trailing spaces not allowed  no-trailing-spaces
  61:75  error  Trailing spaces not allowed  no-trailing-spaces
  62:39  error  Trailing spaces not allowed  no-trailing-spaces
  63:64  error  Trailing spaces not allowed  no-trailing-spaces
  64:60  error  Trailing spaces not allowed  no-trailing-spaces
  66:79  error  Trailing spaces not allowed  no-trailing-spaces
  67:19  error  Trailing spaces not allowed  no-trailing-spaces
  68:70  error  Trailing spaces not allowed  no-trailing-spaces
  69:75  error  Trailing spaces not allowed  no-trailing-spaces
  70:69  error  Trailing spaces not allowed  no-trailing-spaces
  71:73  error  Trailing spaces not allowed  no-trailing-spaces
  73:72  error  Trailing spaces not allowed  no-trailing-spaces
  74:57  error  Trailing spaces not allowed  no-trailing-spaces
  75:29  error  Trailing spaces not allowed  no-trailing-spaces
  77:66  error  Trailing spaces not allowed  no-trailing-spaces
  78:71  error  Trailing spaces not allowed  no-trailing-spaces
  79:22  error  Trailing spaces not allowed  no-trailing-spaces
  81:80  error  Trailing spaces not allowed  no-trailing-spaces
  83:73  error  Trailing spaces not allowed  no-trailing-spaces
  85:79  error  Trailing spaces not allowed  no-trailing-spaces
  86:63  error  Trailing spaces not allowed  no-trailing-spaces
  88:76  error  Trailing spaces not allowed  no-trailing-spaces
  89:12  error  Trailing spaces not allowed  no-trailing-spaces
  90:75  error  Trailing spaces not allowed  no-trailing-spaces
  91:80  error  Trailing spaces not allowed  no-trailing-spaces
  92:57  error  Trailing spaces not allowed  no-trailing-spaces
  94:79  error  Trailing spaces not allowed  no-trailing-spaces
  95:9   error  Trailing spaces not allowed  no-trailing-spaces
  96:66  error  Trailing spaces not allowed  no-trailing-spaces
  97:26  error  Trailing spaces not allowed  no-trailing-spaces

/home/wblankenship/Development/node-restify/lib/plugins/bunyan.js
  13:79  error  Trailing spaces not allowed  no-trailing-spaces
  15:3   error  Trailing spaces not allowed  no-trailing-spaces
  20:3   error  Trailing spaces not allowed  no-trailing-spaces
  26:80  error  Trailing spaces not allowed  no-trailing-spaces

/home/wblankenship/Development/node-restify/lib/plugins/conditionalRequest.js
  183:3   error  Trailing spaces not allowed  no-trailing-spaces
  187:3   error  Trailing spaces not allowed  no-trailing-spaces
  191:3   error  Trailing spaces not allowed  no-trailing-spaces
  193:3   error  Trailing spaces not allowed  no-trailing-spaces
  199:3   error  Trailing spaces not allowed  no-trailing-spaces
  205:12  error  Trailing spaces not allowed  no-trailing-spaces
  212:3   error  Trailing spaces not allowed  no-trailing-spaces
  214:3   error  Trailing spaces not allowed  no-trailing-spaces

/home/wblankenship/Development/node-restify/lib/plugins/cpuUsageThrottle.js
   80:3   error  Trailing spaces not allowed  no-trailing-spaces
   88:3   error  Trailing spaces not allowed  no-trailing-spaces
   97:3   error  Trailing spaces not allowed  no-trailing-spaces
  130:74  error  Trailing spaces not allowed  no-trailing-spaces
  132:67  error  Trailing spaces not allowed  no-trailing-spaces

/home/wblankenship/Development/node-restify/lib/plugins/date.js
  21:75  error  Trailing spaces not allowed  no-trailing-spaces
  22:73  error  Trailing spaces not allowed  no-trailing-spaces
  23:50  error  Trailing spaces not allowed  no-trailing-spaces
  26:33  error  Trailing spaces not allowed  no-trailing-spaces

/home/wblankenship/Development/node-restify/lib/plugins/gzip.js
  31:67  error  Trailing spaces not allowed  no-trailing-spaces
  33:75  error  Trailing spaces not allowed  no-trailing-spaces
  34:24  error  Trailing spaces not allowed  no-trailing-spaces
  38:77  error  Trailing spaces not allowed  no-trailing-spaces
  39:57  error  Trailing spaces not allowed  no-trailing-spaces
  41:3   error  Trailing spaces not allowed  no-trailing-spaces

/home/wblankenship/Development/node-restify/lib/plugins/inflightRequestThrottle.js
  12:3  error  Trailing spaces not allowed  no-trailing-spaces
  16:3  error  Trailing spaces not allowed  no-trailing-spaces
  19:3  error  Trailing spaces not allowed  no-trailing-spaces
  33:3  error  Trailing spaces not allowed  no-trailing-spaces

/home/wblankenship/Development/node-restify/lib/plugins/metrics.js
  83:68  error  Trailing spaces not allowed  no-trailing-spaces
  84:70  error  Trailing spaces not allowed  no-trailing-spaces
  85:65  error  Trailing spaces not allowed  no-trailing-spaces

/home/wblankenship/Development/node-restify/lib/plugins/multipartBodyParser.js
  120:79  error  Trailing spaces not allowed  no-trailing-spaces
  123:79  error  Trailing spaces not allowed  no-trailing-spaces
  124:76  error  Trailing spaces not allowed  no-trailing-spaces
  125:78  error  Trailing spaces not allowed  no-trailing-spaces

/home/wblankenship/Development/node-restify/lib/plugins/pre/context.js
  10:74  error  Trailing spaces not allowed  no-trailing-spaces

/home/wblankenship/Development/node-restify/lib/plugins/pre/dedupeSlashes.js
  15:3  error  Trailing spaces not allowed  no-trailing-spaces

/home/wblankenship/Development/node-restify/lib/plugins/pre/pause.js
  52:31  error  Trailing spaces not allowed  no-trailing-spaces
  53:54  error  Trailing spaces not allowed  no-trailing-spaces
  54:54  error  Trailing spaces not allowed  no-trailing-spaces

/home/wblankenship/Development/node-restify/lib/plugins/pre/prePath.js
  39:48  error  Trailing spaces not allowed  no-trailing-spaces

/home/wblankenship/Development/node-restify/lib/plugins/pre/reqIdHeaders.js
   9:75  error  Trailing spaces not allowed  no-trailing-spaces
  10:66  error  Trailing spaces not allowed  no-trailing-spaces

/home/wblankenship/Development/node-restify/lib/plugins/pre/strictQueryParams.js
  28:47  error  Trailing spaces not allowed  no-trailing-spaces
  29:79  error  Trailing spaces not allowed  no-trailing-spaces

/home/wblankenship/Development/node-restify/lib/plugins/pre/userAgent.js
  26:75  error  Trailing spaces not allowed  no-trailing-spaces

/home/wblankenship/Development/node-restify/lib/plugins/query.js
  10:65  error  Trailing spaces not allowed  no-trailing-spaces
  11:80  error  Trailing spaces not allowed  no-trailing-spaces
  12:53  error  Trailing spaces not allowed  no-trailing-spaces
  14:3   error  Trailing spaces not allowed  no-trailing-spaces
  21:77  error  Trailing spaces not allowed  no-trailing-spaces
  23:72  error  Trailing spaces not allowed  no-trailing-spaces
  24:19  error  Trailing spaces not allowed  no-trailing-spaces
  26:76  error  Trailing spaces not allowed  no-trailing-spaces
  28:79  error  Trailing spaces not allowed  no-trailing-spaces
  32:80  error  Trailing spaces not allowed  no-trailing-spaces
  34:80  error  Trailing spaces not allowed  no-trailing-spaces
  36:74  error  Trailing spaces not allowed  no-trailing-spaces
  37:53  error  Trailing spaces not allowed  no-trailing-spaces
  38:74  error  Trailing spaces not allowed  no-trailing-spaces
  40:80  error  Trailing spaces not allowed  no-trailing-spaces

/home/wblankenship/Development/node-restify/lib/plugins/requestExpiry.js
   8:74  error  Trailing spaces not allowed  no-trailing-spaces
   9:76  error  Trailing spaces not allowed  no-trailing-spaces
  11:3   error  Trailing spaces not allowed  no-trailing-spaces
  16:3   error  Trailing spaces not allowed  no-trailing-spaces
  27:3   error  Trailing spaces not allowed  no-trailing-spaces
  29:3   error  Trailing spaces not allowed  no-trailing-spaces
  34:3   error  Trailing spaces not allowed  no-trailing-spaces
  36:75  error  Trailing spaces not allowed  no-trailing-spaces
  38:77  error  Trailing spaces not allowed  no-trailing-spaces
  40:3   error  Trailing spaces not allowed  no-trailing-spaces
  54:73  error  Trailing spaces not allowed  no-trailing-spaces

/home/wblankenship/Development/node-restify/lib/plugins/static.js
  34:79  error  Trailing spaces not allowed  no-trailing-spaces
  43:78  error  Trailing spaces not allowed  no-trailing-spaces
  44:72  error  Trailing spaces not allowed  no-trailing-spaces
  45:80  error  Trailing spaces not allowed  no-trailing-spaces
  46:63  error  Trailing spaces not allowed  no-trailing-spaces
  47:55  error  Trailing spaces not allowed  no-trailing-spaces
  50:3   error  Trailing spaces not allowed  no-trailing-spaces
  51:72  error  Trailing spaces not allowed  no-trailing-spaces
  52:72  error  Trailing spaces not allowed  no-trailing-spaces
  53:73  error  Trailing spaces not allowed  no-trailing-spaces
  54:45  error  Trailing spaces not allowed  no-trailing-spaces
  55:78  error  Trailing spaces not allowed  no-trailing-spaces
  57:74  error  Trailing spaces not allowed  no-trailing-spaces
  58:61  error  Trailing spaces not allowed  no-trailing-spaces
  59:75  error  Trailing spaces not allowed  no-trailing-spaces
  61:66  error  Trailing spaces not allowed  no-trailing-spaces
  63:3   error  Trailing spaces not allowed  no-trailing-spaces
  64:78  error  Trailing spaces not allowed  no-trailing-spaces
  65:77  error  Trailing spaces not allowed  no-trailing-spaces

/home/wblankenship/Development/node-restify/lib/plugins/throttle.js
  180:3   error  Trailing spaces not allowed  no-trailing-spaces
  182:79  error  Trailing spaces not allowed  no-trailing-spaces
  183:78  error  Trailing spaces not allowed  no-trailing-spaces
  184:71  error  Trailing spaces not allowed  no-trailing-spaces
  185:32  error  Trailing spaces not allowed  no-trailing-spaces
  187:78  error  Trailing spaces not allowed  no-trailing-spaces
  188:56  error  Trailing spaces not allowed  no-trailing-spaces
  190:3   error  Trailing spaces not allowed  no-trailing-spaces

/home/wblankenship/Development/node-restify/lib/request.js
   51:25  error  Trailing spaces not allowed  no-trailing-spaces
   53:64  error  Trailing spaces not allowed  no-trailing-spaces
   80:71  error  Trailing spaces not allowed  no-trailing-spaces
   83:3   error  Trailing spaces not allowed  no-trailing-spaces
   92:79  error  Trailing spaces not allowed  no-trailing-spaces
   98:3   error  Trailing spaces not allowed  no-trailing-spaces
  105:3   error  Trailing spaces not allowed  no-trailing-spaces
  193:79  error  Trailing spaces not allowed  no-trailing-spaces
  225:79  error  Trailing spaces not allowed  no-trailing-spaces
  237:66  error  Trailing spaces not allowed  no-trailing-spaces
  305:60  error  Trailing spaces not allowed  no-trailing-spaces
  306:71  error  Trailing spaces not allowed  no-trailing-spaces
  307:72  error  Trailing spaces not allowed  no-trailing-spaces
  366:54  error  Trailing spaces not allowed  no-trailing-spaces
  379:65  error  Trailing spaces not allowed  no-trailing-spaces
  395:54  error  Trailing spaces not allowed  no-trailing-spaces
  407:76  error  Trailing spaces not allowed  no-trailing-spaces
  487:48  error  Trailing spaces not allowed  no-trailing-spaces
  496:67  error  Trailing spaces not allowed  no-trailing-spaces
  541:75  error  Trailing spaces not allowed  no-trailing-spaces
  554:3   error  Trailing spaces not allowed  no-trailing-spaces
  559:3   error  Trailing spaces not allowed  no-trailing-spaces
  716:42  error  Trailing spaces not allowed  no-trailing-spaces
  717:70  error  Trailing spaces not allowed  no-trailing-spaces
  718:37  error  Trailing spaces not allowed  no-trailing-spaces
  719:80  error  Trailing spaces not allowed  no-trailing-spaces
  747:3   error  Trailing spaces not allowed  no-trailing-spaces
  778:40  error  Trailing spaces not allowed  no-trailing-spaces
  779:74  error  Trailing spaces not allowed  no-trailing-spaces

/home/wblankenship/Development/node-restify/lib/response.js
   38:25  error  Trailing spaces not allowed  no-trailing-spaces
   40:70  error  Trailing spaces not allowed  no-trailing-spaces
   52:58  error  Trailing spaces not allowed  no-trailing-spaces
  131:77  error  Trailing spaces not allowed  no-trailing-spaces
  132:76  error  Trailing spaces not allowed  no-trailing-spaces
  160:61  error  Trailing spaces not allowed  no-trailing-spaces
  165:3   error  Trailing spaces not allowed  no-trailing-spaces
  168:3   error  Trailing spaces not allowed  no-trailing-spaces
  171:3   error  Trailing spaces not allowed  no-trailing-spaces
  176:68  error  Trailing spaces not allowed  no-trailing-spaces
  184:66  error  Trailing spaces not allowed  no-trailing-spaces
  185:57  error  Trailing spaces not allowed  no-trailing-spaces
  186:32  error  Trailing spaces not allowed  no-trailing-spaces
  284:75  error  Trailing spaces not allowed  no-trailing-spaces
  285:34  error  Trailing spaces not allowed  no-trailing-spaces
  286:80  error  Trailing spaces not allowed  no-trailing-spaces
  287:40  error  Trailing spaces not allowed  no-trailing-spaces
  288:80  error  Trailing spaces not allowed  no-trailing-spaces
  304:80  error  Trailing spaces not allowed  no-trailing-spaces
  305:34  error  Trailing spaces not allowed  no-trailing-spaces
  526:44  error  Trailing spaces not allowed  no-trailing-spaces
  651:80  error  Trailing spaces not allowed  no-trailing-spaces
  660:75  error  Trailing spaces not allowed  no-trailing-spaces
  661:52  error  Trailing spaces not allowed  no-trailing-spaces
  682:74  error  Trailing spaces not allowed  no-trailing-spaces
  697:74  error  Trailing spaces not allowed  no-trailing-spaces

/home/wblankenship/Development/node-restify/lib/server.js
  257:41  error  Trailing spaces not allowed  no-trailing-spaces
  643:5   error  Trailing spaces not allowed  no-trailing-spaces
  644:15  error  Trailing spaces not allowed  no-trailing-spaces
  645:9   error  Trailing spaces not allowed  no-trailing-spaces
  655:15  error  Trailing spaces not allowed  no-trailing-spaces
  656:21  error  Trailing spaces not allowed  no-trailing-spaces
  724:68  error  Trailing spaces not allowed  no-trailing-spaces
  737:11  error  Trailing spaces not allowed  no-trailing-spaces
  741:12  error  Trailing spaces not allowed  no-trailing-spaces

/home/wblankenship/Development/node-restify/test/server.test.js
  1140:9  error  Expected indentation of 4 spaces but found 8  indent
  1142:9  error  Expected indentation of 4 spaces but found 8  indent
  1150:9  error  Expected indentation of 4 spaces but found 8  indent
  1158:9  error  Expected indentation of 4 spaces but found 8  indent
  1165:9  error  Expected indentation of 4 spaces but found 8  indent
  1169:5  error  Expected indentation of 0 spaces but found 4  indent

✖ 226 problems (226 errors, 0 warnings)

tools/mk/Makefile.targ:135: recipe for target 'check-style' failed
<code>
<summary>

**Comment by hekike** [comment]
@yunong didn't you have a similar issue before?

**Comment by DonutEspresso** [comment]
Generally 👍  on the idea! Not sure how it will feel in practice, as you noted with a lot of the inline functional stuff. Willing to give it a shot and see how it goes, though.

**Comment by yunong** [comment]
@hekike is Travis running pre push?

**Comment by hekike** [comment]
@yunong yes, I really don't know what's happening. It's okay on my machine and TravisCI but you and @retrohacker reported some spacing issues on your machines.

**Comment by hekike** [comment]
@yunong @retrohacker I fixed whitespaces in another PR: https://github.com/restify/node-restify/pull/1535

However, I'm still not sure why it caused an issue only on certain machines, strange.

**Pull request merged**
