### PR TITLE
option for static serve to check if-modified-since

### PR DESCRIPTION
**Pull request by avimar**
Mentioned in #993

### CODE REVIEW

**Comment by avimar** [comment]
Is there a reason why this build failed? It looks like a travis config issue.

**Comment by micahr** [comment]
Looks like an eslint config issue. I've updated master with the appropriate change.

**Comment by avimar** [comment]
I fixed some lint issues...

**Comment by DonutEspresso** [comment]
It might need to - saw something similar filed against ecstatic a little bit ago:
https://github.com/jfhbrook/node-ecstatic/pull/179

**Comment by DonutEspresso** [comment]
Thanks for the PR! Can you elaborate with the issue with windows, I'm not familiar.

**Comment by avimar** [comment]
Date is still an issue in `node v4.3.0`...

but if you do (windows) `curl "http://localhost:8000/bower.json" -H "Connection: keep-alive" -H "If-Modified-Since: 275760-10-13`
You get: `{"code":"InternalError","message":"illegal access"}"` but it doesn't crash the node process since restify handles exceptions.

So - if someone sends a super malformed request, it fails. (It doesn't show up in my logs..) Does that matter?

**Comment by DonutEspresso** [comment]
In 5.x the uncaughtException handlers are going to be off by default, so yes, this would crash the server.

**Comment by avimar** [comment]
I had borrowed some of the code from here which will then also also crash:
https://github.com/restify/node-restify/blob/4.x/lib/plugins/conditional_request.js#L122
`if (Date.parse(mtime) <= Date.parse(ctime)) {`

but later, https://github.com/restify/node-restify/blob/4.x/lib/plugins/conditional_request.js#L162 is wrapped in a try/catch, I guess that's what we have to do?

This was pushed upstream in v8 to not throw an exception, but current versions of node still throw.

**Comment by DonutEspresso** [comment]
Yeah, I think it's reasonable to wrap in try/catch like in the conditional request plugin. Thanks for digging into it!

**Comment by langflashcards** [comment]
is it known when it can be expected ot be merged?

**Comment by DonutEspresso** [comment]
I think once @avimar gets a chance to add the try/catch in there I'd be happy to merge this in. 

That said, I think we'd like if you could file this PR against the restify/plugins repo instead. For our next 5.x release, all major plugins will be removed from core.

**Comment by DonutEspresso** [comment]
Closing in favor of restifyplugins#23

**Comment by avimar** [comment]
This was supposed to be a backport until the next restify version...

**Pull request closed without merging**
