### PR TITLE
docs(README): remove NSP badge

### PR DESCRIPTION
**Pull request by hekike**
The current `nsp` badge is static, it's always green.
However, it's probably correct at the moment when a new PR is merged to master, as CI checks it.
It's not necessarily valid at any point in the time, like now.

# Changes

- remove "always green" `nsp` badge from README.md

### CODE REVIEW

**Comment by DonutEspresso** [comment]
Hm, there is a `./tools/nspBadge.js` script that updates the badge whenever we run `make nsp`. Does that work for you?

**Comment by hekike** [comment]
@DonutEspresso yes but it's misleading, as it's calculated when CI runs, and a vulnerability can be discovered later.

Imagine the following scenario:

1. PR is merged, CI generates a green nsp badge
2. Vulnerability is discovered a day later
3. You check restify's Readme -> you think everything is cool

**Comment by DonutEspresso** [comment]
Hm that's true - are there any ways to keep this "live"? Or are we better off not showing it at all? I figured something was better than nothing, but that's probably not great if it's misleading. :(

**Comment by hekike** [comment]
Snyk has a badge, but it showed zero when we had a known vulnerability based on `nsp` :/
https://snyk.io/test/github/restify/node-restify/badge.svg

Would be nice to have something for nsp as well.

**Comment by retrohacker** [comment]
I'm :+1: on removing this, it is very misleading since `nsp`'s database is dynamic and the image is static. There will never be a time where we merge a non-green `nsp` badge.

**Comment by retrohacker** [comment]
Opening another PR to remove the makefile stuffs

**Pull request closed without merging**
