### PR TITLE
Doc site

### PR DESCRIPTION
**Pull request by retrohacker**
## Pre-Submission Checklist

- [X] Opened an issue discussing these changes before opening the PR
- [X] Ran the linter and tests via `make prepush`
- `N/A` Included comprehensive and convincing tests for changes

## Issues

Supports #912

We are moving to a simple jekyll based website. The source will live at https://github.com/restify/restify.github.io (maintainers already have access to this).

# Changes

* Allows our template to live in the restify.github.io repo while our documentation lives in the node-restify repo. We add node-restify as a submodule and remove all recursive submodules so github pages can do a full build.
* Add's jekyll front-matter to docs
* Re-organizes docs to follow layout of sidebar on the doc site
* Removes content that is an awkward fit

Snapshot:

screenshot from 2017-06-30 15-43-34

### CODE REVIEW

**Comment by stevehipwell** [comment]
@retrohacker - I'd like to update the TypeScript definitions for Restify and to do so it would help if I could have access to the new documentation.

**Comment by retrohacker** [comment]
Only tests failing are for Node.js v8, going ahead and merging to release the new doc site. Will pull over the doc updates from the old WIP site here soon.

**Comment by retrohacker** [comment]
The new website is available at https://restify.github.io/

Will work on migrating DNS over this week.

**Comment by stevehipwell** [comment]
@retrohacker - All I'm getting is a single marketing page, where are the actual docs?

**Comment by stevehipwell** [comment]
@retrohacker - If I request the desktop site it works, so I assume it's a responsive bug.

**Comment by retrohacker** [comment]
@stevehipwell ah! Good catch. Just pushed a fix. Looks like it was collapsing into a drop-down menu, but the hamburger icon was black on a black background! Should be visible now :smile:

**Pull request merged**
