### PR TITLE
breaking: update travis targets

### PR DESCRIPTION
**Pull request by DonutEspresso**

### CODE REVIEW

**Comment by DonutEspresso** [comment]
We're in a weird place right now - 10 isn't LTS yet (but almost!) so branches seem to be pointing to all the versions around it. Hardcoded all the relevant versions for now.

**Comment by hekike** [comment]
10 is LTS now ;)

**Comment by sean3z** [comment]
@DonutEspresso @hekike Any objections moving forward with this one? I suspect not but, want to confirm as this would imply "officially" dropping support for Node 4  🙂 and we'd presumably also want to update the engine target in [package.json](https://github.com/restify/node-restify/blob/master/package.json#L92-L94)

**Comment by DonutEspresso** [comment]
No concerns here - though I think technically dropping 4 should be a breaking change. I'll rename the PR to reflect that.

**Comment by rajatkumar** [comment]
This is addressed as part of restify v8 release. Closing this PR.

**Pull request closed without merging**
