### PR TITLE
Removing replace logic for route name

### PR DESCRIPTION
**Pull request by sean3z**
GH Issue #882

This PR ensures that a given route name is returned the same as specified by removing the (seemingly unnecessary) replace logic. As it stands, route names provided will be stored with any `/[^\w]/g` characters removed. This effectively makes them useless as a reference outside of the `router.render()` usage.

```js
app.get({
  name: 'my-awesome-route',
  path: '/my-awesome-route'
}, ...)
```

Currently provides the following `req.route` object

```js
route: { 
  name: 'myawesomeroute',
  path: '/my-awesome-route',
  method: 'GET'
}
```

The change here proposes that the `name` property should instead be, `my-awesome-route`

### CODE REVIEW

**Comment by micahr** [comment]
Thanks for adding this @sean3z. Since this involves changing route names, and how they are matched, we should probably rev at least a minor version.

**Comment by kodypeterson** [comment]
Nice work @sean3z always room to shave off some processing time :smile:

**Comment by sean3z** [comment]
@micahr done :)

**Comment by micahr** [comment]
@sean3z Sorry, I meant that for our future reference. We won't want to rev to 4.1.0 until we are ready to do another release.

**Comment by sean3z** [comment]
ah fair enough, I've reverted the bump

**Comment by micahr** [comment]
@yunong - This should be good to go, any objections?

**Pull request merged**
