### PR TITLE
Create unit tests for sanitizePath

### PR DESCRIPTION
**Pull request by retrohacker**
* Create unit tests for sanitizePath

### CODE REVIEW

**Comment by DonutEspresso** [comment]
Hmm is there overlap between this and the plugins sanitize path plugin?

**Comment by retrohacker** [comment]
There is, whats more is that it doesn't look like the `util.sanitizePath` function is used anywhere. I'm :+1: on moving this implementation over to the plugin and migrating the tests to that API. The plugin's implementation is done with a for loop.

**Comment by retrohacker** [comment]
@alex ready for another review :smile:

**Comment by DonutEspresso** [comment]
LGTM! Rebase and let's get this in. 🎉

**Pull request merged**
