### PR TITLE
link build badge to master branch

### PR DESCRIPTION
**Pull request by a0viedo**

### CODE REVIEW

**Comment by DonutEspresso** [comment]
Thanks! I'll merge this in after we merge in 5.x.

**Comment by retrohacker** [comment]
Hey @a0viedo,

We really appreciate you pointing this out. As of now, we are still a ways away from the release of 5.x, and this change now has a merge conflict with the README. It being such a small change (in terms of line count), I'm going to close this in favor of updating the badge along with the 5.x release in the future.

If you disagree with this, please comment and we can revisit :smile: if you are wanting to see your name up on the contributors tab, follow the 5.x milestone and open a PR closer to when its complete, we will be happy to merge then :heart:

**Comment by a0viedo** [comment]
hey @retrohacker, there's real benefits from linking particularly to the master branch: if you don't then a possibly failing build from another branch will turn the badge red. I only think that's confusing for everyone

**Comment by retrohacker** [comment]
I absolutely agree with you @a0viedo :smile:

I'd like to see us change the way we treat branches. I'm working on getting 5.x out the door ASAP (can't cut a release yet, there are still some things that need to be fixed before its ready to go out). After 5.x ships, I'm planning on implementing what is being discussed here: https://github.com/restify/node-restify/issues/913#issuecomment-299964604

I'd love to get your feedback on that process, I'm hoping it will help allow us to have a _stable_ and _up to date_ master branch.

**Comment by retrohacker** [comment]
As of right now, 5.x is where active development is happening and 4.x is receiving patches as necessary. The new flow will treat master as the current version released to npm and everything else will just be staging changes to be released in batches.

**Pull request closed without merging**
