### PR TITLE
Restify errors

### PR DESCRIPTION
**Pull request by DonutEspresso**
New errors module, all broken out from core. Not ready for merging, yet, but want a place to stage the diff and discuss potential impact to restify core.

### CODE REVIEW

**Comment by DonutEspresso** [comment]
Seems like older versions of npm don't like the https dependency in package.json. Guess we'll wait to publish restify-errors, if possible.

**Comment by DonutEspresso** [comment]
@yunong this looks good to go - if you have pub rights for restify-errors, once that's up I can change this from a git url to the actual version.

**Comment by yunong** [comment]
Can you please add a CHANGES.md to the errors repo?

**Comment by DonutEspresso** [comment]
LGTM, now. Merge unless you have any other requests.

**Comment by yunong** [comment]
Looks good. Feel free to merge.

On Monday, August 24, 2015, Alex Liu <notifications@github.com> wrote:

> LGTM, now. Merge unless you have any other requests.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/restify/node-restify/pull/844#issuecomment-134410394>.
>


-- 
Via mobile

**Pull request merged**
